version = 1

[[annotations]]
path = [
    ".gitignore",
    ".gitlab-ci.yml",
    ".gitmodules",
    ".pre-commit-config.yaml",
    ".python-version",
    ".vscode/settings.json",
    "config/*.toml",
    "dependencies/hashes",
    "pyproject.toml",
    "scripts/*.sh",
    "tests/resources/*.toml",
    "uv.lock",
]
precedence = "override"
SPDX-FileCopyrightText = "2024 Tadej Novak"
SPDX-License-Identifier = "MPL-2.0"
