labels = ["Single muons, 70 < $p_\\mathrm{T}$ < 90 GeV, -4 < $\\eta$ < 4"]
name = "Muon pt70-90 etaFull"
events = 640000

[process]
type = "single_particle"
particle = "mu"
pt = [70, 90]
eta = [-4, 4]

[simulation]
type = "geant4"
disable_secondaries = true
