labels = ["Single muons, $p_\\mathrm{T}$ = 100 GeV, 0.2 < $\\eta$ < 0.25"]
name = "Muon 100 GeV Barrel Test"
events = 6400

[process]
type = "single_particle"
particle = "mu"
pt = 100
eta = [0.2, 0.25]

[simulation]
type = "geant4"
disable_secondaries = true
