labels = ["Single muons, $p_\\mathrm{T}$ = 100 GeV, $\\eta$ = 0.2"]
name = "Muon 100 GeV Barrel Narrow"
events = 160000

[process]
type = "single_particle"
particle = "mu"
pt = 100
eta = 0.2

[simulation]
type = "geant4"
secondaries_min_pt = 0.01
